initial_load:
  include: 
    - path: "/root/keyao/Checkpoints/ZeroCkpt/ZeroCkpt2/scripts/data/multi_card/*.log"
  type: raw
  global_tags: [origin]

steps:
  - processor: parse_multi_stalltime_with_timestamp
    inputs: initial
    output: parsed
  
  - processor: filter_table
    inputs: parsed
    output: filtered1
    params:
      conditions:
        ckpt_freq: in [100, 150, 200]
        batch_size: in [4]

  - processor: filter_by_condition
    inputs: filtered1
    output: filtered
    params:
      # 自定义定义过滤条件
      filter_expression: "record_type == 'Step' & step > total_steps - 8"  # P.S. step > step.max() - 10 is OK

  - processor: plot_grouped_bar
    inputs: filtered
    output: throughput
    params:
      # figsize: [40,6]
      
      main_group_col: "ckpt_type"
      sub_group_col: "ckpt_freq"
      # col_col: "model_name"  # 按模型名称分列
      value_col: "tokens_per_sec" # throughput
      title: ""
      xlabel: "Checkpoint Scheme"
      yticks_num: 5
      ylabel: "Throughput (Tokens/s)"
      grid: False
      show_main_group_separators: True

      legend_loc: "lower center"
      legend_bbox_to_anchor: [0.5, 1] # 使用 [0.5, Y] 来垂直移动，Y值小于1
      legend_ncol: 4 # 保持横向排列
      legend_frameon: False # 可以去掉图例边框，让它更清爽

      # 字体配置：全局改为Times New Roman
      title_fontfamily: "Times New Roman"       # 总标题字体
      xlabel_fontfamily: "Times New Roman"      # x轴标签字体
      ylabel_fontfamily: "Times New Roman"      # y轴标签字体
      xticks_fontfamily: "Times New Roman"      # x轴刻度字体
      yticks_fontfamily: "Times New Roman"      # y轴刻度字体
      subplot_title_fontfamily: "Times New Roman"  # 子图标题字体
      legend_fontfamily: "Times New Roman"      # 图例字体

      colors:
        100: ${COLOR_100}
        150: ${COLOR_150}
        200: ${COLOR_200}
      main_group_order:
        - "deepspeed"
        - "torch_snapshot"
        - "torch_dcp"
        - "datastates_llm"
        - "torch_dcp_async"
        - "py_async"
        - "cpp_overlap"
        - "grad"
        - "half_zero"
        - "ideal"

      main_group_labels:
        deepspeed: ${DEEPSPEED}
        torch_snapshot: ${TORCH_SNAPSHOT}
        torch_dcp: ${TORCH_DCP}
        datastates_llm: ${DATASTATES_LLM}
        torch_dcp_async: ${TORCH_DCP_ASYNC}
        grad: ${GRAD}
        half_zero: ${HALF_ZERO}
        py_async: ${PY_ASYNC}
        cpp_overlap: ${CPP_OVERLAP}
        ideal: ${IDEAL}
      
      aggregate_func: "max"  # 取最大值
      show_bar_values: True
      bar_value_format: '{:.0f}'   # 显示三位小数
      bar_value_fontsize: 12       # 字体大小设为12
      bar_value_rotation: 90       # 垂直显示
      bar_width: 0.2
      main_group_gap: 0.1
      sub_group_gap: 0.01
      xlabel_pad: 15
      figsize: [18, 5]
      ylim: [0, 14000]
      # font size
      xlabel_fontsize: 25
      ylabel_fontsize: 25
      xticks_fontsize: 19
      yticks_fontsize: 20
      legend_fontsize: 20
      bar_value_fontsize: 19.5

final_output:
  - name: throughput
    export: multi_card_test.pdf